### ISSUE TITLE
Code highlighting with backticks

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/sphinxcontrib-jupyter#104]
It doesn't appear that text in rst enclosed in backticks is being highlighted.

**Comment by mmcky** [comment]
@natashawatkins can you give me some examples? The inline is typically rendered as a gray cell around the contents. 

Also markdown only typically supports rendering using fenced code blocks using three backticks. 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

We could probably add this as a custom feature but I think they would need to be included as inline html markup

**Comment by natashawatkins** [comment]
So the issue is the sphinx converted is somehow getting rid of the backticks, because the backticks do work in a Jupyter notebook. See for example from the numpy lecture...

<img width="772" alt="screen shot 2018-09-24 at 3 37 18 pm" src="https://user-images.githubusercontent.com/21038129/45974632-e727fc80-c00f-11e8-83c2-753812832ea1.png">
<img width="774" alt="screen shot 2018-09-24 at 3 37 39 pm" src="https://user-images.githubusercontent.com/21038129/45974637-eabb8380-c00f-11e8-8a0f-ae84962a0a75.png">


The above picture I added a cell with what Jupyter notebook renders with backticks

**Comment by mmcky** [comment]
thanks @natashawatkins that example is helpful. I will dig into this on Monday.

**Comment by mmcky** [comment]
hey @natashawatkins I think you'll find the source has a single backtick for the ones that aren't highlighted. For inline code examples you can use two backticks as per the sphinx documentation
http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
This is technically an in line literal markup but that is typically all that is required.

We could support inline roles using single backticks if we need to but probably isn't adding much value for the highlighting.

**Comment by natashawatkins** [comment]
I think we should support it because that's how nearly all highlighting is done in the currest rst files

**Comment by natashawatkins** [comment]
I updated jupinx and this has now been fixed
