### ISSUE TITLE
Rendering of small equations with labels has layout issues

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/sphinxcontrib-jupyter#117]
The jupinx master seems to have flaws in the display with equations.  Create something like
```rst
.. math::
    :label: test

    v = p + \beta v
```
And the generated HTML is
```html
<a id='equation-test'></a>
<table width=100%><tr style='background-color: #FFFFFF !important;'>
<td width=10%></td>
<td width=80%>
$$
v = p + \beta v
$$
</td><td width=10% style='text-align:center !important;'>
(1)
</td></tr></table>
```
which wrapped the equation in a weird way because of the decrease in the width of the table

cc: @mmcky  any thoughts on easy workaround?

**Comment by mmcky** [comment]
thanks @jlperla. I will add your example to our test set and check it out. Perhaps our css is altering the look of labeled equations.

**Comment by mmcky** [comment]
I also like you're idea of using latex `\tag{#}`

**Comment by mmcky** [comment]
- [ ] add to test case ``code_blocks``

**Comment by mmcky** [comment]
I have added the above test case to the test notebook ``math.rst`` and it renders like this:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/8263752/46324965-8f097f80-c639-11e8-9736-50002ce5de36.png">

**Comment by mmcky** [comment]
is your issue at the notebook level or post `nbconvert` to html?

**Comment by jlperla** [comment]
Notebooks. I am not sure how to generate html yet!

**Comment by mmcky** [comment]
are you getting rendering that is different to the screenshot above?

**Comment by jlperla** [comment]
![image](https://user-images.githubusercontent.com/13106721/46327904-00edb480-c5b9-11e8-9eab-68f2d31655eb.png)

The above is a rendered from the following rst in Jupytelab (generated using ubuntu on WSL, not that it matters, and displaying in chrome)
```rst

Fixed-Point Maps
----------------------------

Consider the simple equation, where the scalars :math:`p,\beta` are given, and  :math:`v` is the scalar we wish to solve for

.. math::
    :label: vfixed

    v = p + \beta v

Of course, in this simple example, with parameter restrictions this can be solved as :math:`v = p/(1 - \beta)`

Rearrange the equation in terms of a map :math:`f(x) : \mathbb R \to \mathbb R`

.. math::

    v = f(v)

where

.. math::

    f(v) := p + \beta v
 

Therefore, a fixed point :math:`v^*` of :math:`f(\cdot)` is a solution to the above problem
```

**Comment by jlperla** [comment]
Key version numbers from `conda list` are
```
sphinx                    1.7.4                    py36_0
sphinxcontrib             1.0              py36h6d0f590_1
sphinxcontrib-bibtex      0.4.0                     <pip>
sphinxcontrib-jupyter     0.2b0.dev20180929           <pip>
sphinxcontrib-jupyter     0.2b0.dev20180827           <pip>
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1
```
But I think this is probably a html/css problem, as opposed to a generation problem

**Comment by mmcky** [comment]
I'm using `sphinx=1.7.8` but as you say I don't think that is the issue (as the html output is the same). Could a local extension be altering the alignment of equations. My environment has not `jupyter` extensions installed with no specific html/css adjustment to base jupyter.

**Comment by jlperla** [comment]
My jupyter has no extensions, but perhaps it is old.  The versions are
```
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36he59e554_1
jupyter_core              4.4.0            py36h7c827e3_0
jupyterlab                0.32.1                   py36_0
jupyterlab_launcher       0.10.5                   py36_0
```
I will to upgrade jupyterlab tomorrow and see what happens

**Comment by mmcky** [comment]
I mainly just `jupyter notebook` rather than jupyterlab ... I will test with jupyterlab on my end also.

**Comment by jlperla** [comment]
I think that most jupyterhub installations are moving quickly to `jupyterlab`, so it might make sense to test there as the primary interface.  But, if this is a jupyter vs. jupyterhub issue, I think it also points out that there is only so much you can do to deal with different versions of jupyterhub

**Comment by bayeswhu** [comment]
@mmcky Is there any method to enlarge the labelled equations? As you mentioned, they are a little bit smaller than the equations without labels. Especially when I tried to present the notebook in slides (with RISE), I found it is hard to read.

**Comment by arnavs** [comment]
Hi @mmcky, just wanted to chime in that I can reproduce this issue on https://compare-lectures.quantecon.org/jl/jupinx_test.html 

```
<table width=100%><tr style='background-color: #FFFFFF !important;'>
<td width=10%></td>
<td width=80%>
$$
v = f(v)
$$
</td><td width=10% style='text-align:center !important;'>

</td></tr></table><p>And want to link to it in text <a href="julia_by_example.html#equation-fixed-point-map">(1)</a></p>
```

**Comment by mmcky** [comment]
we could wrap the tables in a class and adopt a local mathjax resize in our theme for now.

https://stackoverflow.com/questions/19086152/changing-mathjaxs-font-size

**Comment by mmcky** [comment]
A fix has been implemented in https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/152

**Comment by jlperla** [comment]
Was this solution used in the latest generation of the notebooks?  I just downloaded a notebook geenrated from the mccall lecture and in jupyterlab it looks like
![image](https://user-images.githubusercontent.com/13106721/49040355-335dfd00-f177-11e8-969e-05535c7801c1.png)

On the other hand, to look at the julia examples file, the HTML is a little odd in that the numbered equations are larger than the other ones:
![image](https://user-images.githubusercontent.com/13106721/49040445-7029f400-f177-11e8-94f5-dab11477898b.png)

and the of numbered equations are still an issue with weird splitting
![image](https://user-images.githubusercontent.com/13106721/49040519-a1a2bf80-f177-11e8-8ab6-295cc7738b4f.png)

**Comment by mmcky** [comment]
these issues should be fixed by https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/154 when merged.

**Comment by mmcky** [comment]
#154 is merged so closing this issue.
