### ISSUE TITLE
Numbered equations break display of ipynb in github's built in viewer

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/sphinxcontrib-jupyter#127]
Take one of the generated notebooks from sphinx with equation numbers, check it into github, and then go to the repo.   You will see that the html around the equation ends up breaking display.  See the attached

![image](https://user-images.githubusercontent.com/13106721/46516183-224eda80-c81d-11e8-902f-00cfac5ac7f9.png)

**Comment by jlperla** [comment]
@mmcky  I checked this in nbviewer and it seems to not be an issue there.

**Comment by mmcky** [comment]
thanks @jlperla `nbviewer` is much closer to `nbconvert` output. Github is a more limited viewing platform for notebooks. I have had a few things break on GitHub.

**Comment by jlperla** [comment]
OK, then let me close this.  If the numbering works in nbviewer, then no need to force it to support the github viewer (since links using nbviewer are so easy to add on README)
