### ISSUE TITLE
Math rendering of `\trace`

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/sphinxcontrib-jupyter#133]
Doesn't appear to render properly
![image](https://user-images.githubusercontent.com/21038129/47057781-2f11ed80-d190-11e8-869f-d487a2ff94df.png)

**Comment by FelipeMaldonado** [comment]
Is it declare beforehand? because the operator trace doesn't exist by default on Tex.

**Comment by natashawatkins** [comment]
It was from `lqcontrol.rst`

**Comment by natashawatkins** [comment]
This is still an issue after I updated  jupinx

**Comment by mmcky** [comment]
`trace` has been replaced and is rendering correctly on `lqcontrol`.
