### ISSUE TITLE
Links with escaped characters

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/sphinxcontrib-jupyter#149]
Came up in https://github.com/quantecon/lecture-source-jl/pulls/384

In particular, we have wikipedia links like 

```
`field <https://en.wikipedia.org/wiki/field_\(mathematics\)>`_
```

Which work fine in the generated Jupyter, but it looks like the trailing `)` is missing in the HTML (see the `generic_programming` lecture for an example). 

cc @jlperla @natashawatkins

**Comment by mmcky** [comment]
Thanks. So the generated output in the notebook has the extra `)` but it looks well formed in the raw `md`. It looks like markdown is capturing the wrong bracket when rendering. 

```md
Thinking back to the mathematical motivation, a [Field](https://en.wikipedia.org/wiki/Field_(mathematics)) is an Ring with a few additional properties, among them

> - a multiplicative inverse: $ a^{-1} $  
- an inverse operation for multiplication: $ a / b = a \cdot b^{-1} $ 
```

and the rendering
![image](https://user-images.githubusercontent.com/8263752/48991620-bd15c680-f187-11e8-8d92-b8b75d97c7c1.png)

**Comment by mmcky** [comment]
I think the only solution here is to replace `(` with `%28` in the notebook

**Comment by mmcky** [comment]
The following PR will fix the bracket issue https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/151 in links. Markdown uses the first ) so they have been replaced with %29 etc.
