### ISSUE TITLE
.. NOTE:: directives rendered in markdown

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/sphinxcontrib-jupyter#15]
Jupinx is rendering `.. NOTE::` directives whereas the lectures ignore these

Example from the [permanent income lecture](https://lectures.quantecon.org/py/perm_income.html):
![image](https://user-images.githubusercontent.com/21038129/33534866-54aedf8e-d8fe-11e7-85f8-d8f67140c25d.png)

**Comment by natashawatkins** [comment]
Also note the issue with footnote rendering

**Comment by mmcky** [comment]
I think this is fixed. 

![image](https://user-images.githubusercontent.com/8263752/67349846-d6401680-f594-11e9-94cc-c3983caa3374.png)

and 

![image](https://user-images.githubusercontent.com/8263752/67349872-e5bf5f80-f594-11e9-9a64-d5ff915237f8.png)
