### ISSUE TITLE
images in jupyter downloads

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/sphinxcontrib-jupyter#163]
We're seeing some issues with the downloaded jupyter notebooks on some platforms (i.e., https://github.com/QuantEcon/lecture-source-jl/issues/502). In particular, some images are too large and overshadowing text. Others have weird sizes (the `getting_started` lecture is a good example of both). 

I think the `height` part of `style="width:100%;height:100%"` is causing the blocked text. 

Can't reproduce on my Mac, but can on Ubuntu and I believe @jlperla can on Windows.

**Comment by mmcky** [comment]
@arnavs can you point me to a specific lecture where this is occuring

**Comment by mmcky** [comment]
Like this?

![image](https://user-images.githubusercontent.com/8263752/51013535-18283f00-15b7-11e9-949f-a444da0d13b2.png)

**Comment by jlperla** [comment]
I think @arnavs said it only failed on windows and osx?

**Comment by jlperla** [comment]
No sorry, he said Ubuntu as well. And you are using jupyter lab, not jupyter notebooks?

**Comment by mmcky** [comment]
ah - thanks! I wasn't. I'll try that.

**Comment by mmcky** [comment]
looking pretty similar for me in jupyterlab also:

![image](https://user-images.githubusercontent.com/8263752/51013722-2dea3400-15b8-11e9-8c6e-c4c6d90e0096.png)

hmm ..

**Comment by mmcky** [comment]
is this a browser thing? I am using `chrome`?

**Comment by mmcky** [comment]
It looks like this issue is currently **resolved** (by unknown source).
