### ISSUE TITLE
Code blocks being generated as non-execute

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/sphinxcontrib-jupyter#166]
When using the latest release (`v1.8.3`) for Sphinx and master, notebooks are generating markdown cells as
```
```julia
...
```
Instead of code cells.
cc: @mmcky

**Comment by mmcky** [comment]
Thanks for the report @Nosferican. I have been away for the a while and just re-parsing this issue list. This should now be fixed with the latest `master` of `sphinxcontrib-jupyter` for `1.8.5`. From `sphinx=2.1.2` it is advised to use ``.. code-block::`` instead of ``.. code::`` also.

**Comment by mmcky** [comment]
Please let me know if you find there are any additional issues.

**Comment by Nosferican** [comment]
Seems to no longer be an issue ([Getting Started](https://lectures.quantecon.org/jl/getting_started_julia/getting_started.html) was the use case I used to verify current behavior). Thanks!
