### ISSUE TITLE
Review 1.8.3 with full QuantEcon Lecture set  ....

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#167]
I need to evaluate upgrading to `1.8.3` from `1.7.9` on the build infrastructure for quantecon.build.lectures.

- [ ] See #166 
- [ ] See #124

**Comment by mmcky** [comment]
I am coordinating this with @arnavs. Your `docker` uses `1.8+`?

**Comment by arnavs** [comment]
@mmcky Currently we're on `1.7.9`:

```

# QuantEcon Python stuff.
RUN pip install quantecon && \
    conda install sphinx=1.7.9 && \
    conda install pybtex=0.21 && \
    pip install qeds && \
    pip install linearmodels && \
    pip install interpolation
```

**Comment by mmcky** [comment]
great @arnavs let's keep using that for now.

**Comment by mmcky** [comment]
@arnavs I have been using `sphinx=1.8.5` to build the latest versions of the site (after we updated for compatibility). I think we can close this issue and you can update Docker if you like.

**Comment by arnavs** [comment]
Sounds good. I'll update the Dockerfile.
