### ISSUE TITLE
DISC: review option jupyter_static_file_path 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#198]
`jupyter_static_file_path` is currently implemented as a list. Should this just be a string?

```
app.add_config_value("jupyter_static_file_path", [], "jupyter")
```

Is there a benefit to using a list? Is this just done to concatenate easily?

**Comment by AakashGfude** [comment]
Probably this was implemented as a list to allow multiple static folders to exist and their files being used. We don't have any requirement as such at present, so maybe we can change it to be a string? @mmcky

**Comment by mmcky** [comment]
this mimics the `html_static` option so I think we should leave this as is. Closing.
