### ISSUE TITLE
Slash before full stop in headings

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/sphinxcontrib-jupyter#215]
**Issue**  -  If there is a dot in headings, then Pandoc is not handling it correctly. 
       MPE vs. Stackelberg   --------->  is reflected as --------->   MPE vs.~Stackelberg 

**Solution**  (as suggested by Matt)  -  Adding a slash in front of  "." 
For example - in .ipynb file
Current -  "MPE vs. Stackelberg"  can be fixed if it can be written as -  "MPE vs\\. Stackelberg"  (only for headings)

**Comment by mmcky** [comment]
@AakashGfude does this help with the edge cases we looked at this afternoon re titles?

**Comment by AakashGfude** [comment]
@mmcky this was handled with the allowing of ascii characters, and adjusting the hyperlink.
