### ISSUE TITLE
FIX: Handling header.raw file for pdf output

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/sphinxcontrib-jupyter#216]
The `.. include:: /_static/includes/header.raw` in rst sources should be handled to produce the desired tex output for pdf pipeline.

**Comment by mmcky** [comment]
@AakashGfude  do you know what this issue is about? Can we close this?

**Comment by AakashGfude** [comment]
@mmcky  yes this is handled. that block is removed from the pdf pipeline
