### ISSUE TITLE
ENH: Adding authors in pdf output

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/sphinxcontrib-jupyter#217]
Preprocessing tex to show author names in the desired pdf output files. 
Steps as of now :-
` replace "% Pygments definitions" with  "    \\author{Thomas J. Sargent and John Stachurski}"+"\n"+"    % Pygments definitions"`

**Comment by mmcky** [comment]
this is now an option in `conf.py` as `jupyter_pdf_author`
