### ISSUE TITLE
FIX: Add `notebook` to requirements

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#234]
I think `notebook` should be added as a requirement for this extension.

**Comment by AakashGfude** [comment]
Hi @mmcky shouldn't it be added to `jupinx` as a requirement, as probably we are not using it in `sphinxcontrib-jupyter` for now.

**Comment by mmcky** [comment]
thanks @AakashGfude. I will transfer this to `jupinx`
