### ISSUE TITLE
Rendering (not ignoring) TODO

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/sphinxcontrib-jupyter#24]
Jupinx is currently rendering TODO notes in the notebooks

From `dyn_stack.rst`

<img width="780" alt="screen shot 2018-01-08 at 7 37 44 pm" src="https://user-images.githubusercontent.com/21038129/34663571-92384156-f4ab-11e7-8e4e-4917dd35c468.png">

**Comment by mmcky** [comment]
thanks @natashawatkins will look at adding this as an option.

**Comment by mmcky** [comment]
thanks @natashawatkins this will be fixed in PR #87. The extension wasn't ignoring ``comments`` which the TODO above was entered in as in the RST.
