### ISSUE TITLE
BUG: Comments for Book PDF (lecture-source-py)

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#301]
- [x] figures are numbered and the label is the path to the static file

<img width="938" alt="image" src="https://user-images.githubusercontent.com/8263752/67912214-57269000-fbdd-11e9-98d9-d127b9add98c.png">

**Comment by mmcky** [comment]
- [ ] missing unicode characters in code blocks. Need to document the necessary `LaTeX` required to support these characters in `verbatim` or `listings`

**Comment by mmcky** [comment]
- [ ] a number of individual `tex` files contain references that are not unique in the book context

```
\hypertarget{index-1}{}
```

**Comment by mmcky** [comment]
- [ ] in `about_python` there is a missing image from the networkx example

![image](https://user-images.githubusercontent.com/8263752/68635261-166b3700-054c-11ea-8527-718229e5b5af.png)

**Comment by AakashGfude** [comment]
- [ ]  creating a config variable to name the generated book pdf
