### ISSUE TITLE
Consider adding the sphinx-extension GitHub topic

### ISSUE THREAD

**Issue by jdillard** [QuantEcon/sphinxcontrib-jupyter#335]
Just wanted to say you should consider adding the sphinx-extension topic, https://github.com/topics/sphinx-extension, to the repo so it is easier for others to find on the GitHub ecosystem. There are currently 94 other sphinx extensions that use that topic.

**Comment by mmcky** [comment]
thanks @jdillard -- will do so. We've been focusing our efforts these past couple of months on [jupyter-book](https://jupyterbook.org/intro.html) which also uses `sphinx` under the hood -- but will revisit this extension soon with a sharper focus on building `jupyter notebooks`.

**Comment by mmcky** [comment]
Done.
