### ISSUE TITLE
ENH: Add support for LaTeX preamble in notebooks

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#36]
Some notebooks in the ``rst2ipynb`` collection have a LaTeX preamble such as

```rst
$$
\def\CC{\bf C}
\def\QQ{\bf Q}
\def\RR{\bf R}
\def\ZZ{\bf Z}
\def\NN{\bf N}
$$
```
it would be good to add support for this in the ``sphinx extension``. This could be useful https://github.com/jupyter/notebook/issues/534

**Comment by natashawatkins** [comment]
We probably should substitute `\RR` with `\mathbb{R}`

**Comment by mmcky** [comment]
We have removed the need to use custom latex preambles for `mathjax` at QuantEcon. So unless anyone else needs this to be implemented. I might close this issue.
