### ISSUE TITLE
Check installation for other projects - Makefile

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#5]
Once ``pip install sphinxcontrib-jupyter`` is setup then need to check if ``Makefile`` will call the ``jupyter`` builder as part of the new default ``Makefile`` format that is generated by ``sphinx-quickstart``. 

Check if we need to register ``jupyter`` as a builder and that ``make jupyter`` works. 

Currently users may need to add to their Makefile a specific call to ``sphinx-build``

**Comment by NickSifniotis** [comment]
@mmcky can confirm (having tested this just now) that if the extension is installed on the system, the default Makefile produced by sphinx-quickstart will call the builder correctly without modification.
