### ISSUE TITLE
Config option for the default language

### ISSUE THREAD

**Issue by nthiery** [QuantEcon/sphinxcontrib-jupyter#59]
Add a config option `jupyter_default_lang`, and use it instead of `python3` in `JupyterCodeTranslator.__init__`

@ocayrol is on it :-)

**Comment by nthiery** [comment]
Implementation in: https://github.com/ocayrol/sphinxcontrib-jupyter/commit/e22fa99fc0483836f890d2c25ee76f27101b55ee
Do you prefer it as a PR?

**Comment by mmcky** [comment]
thanks for the PR #64.
