### ISSUE TITLE
Handling of static files

### ISSUE THREAD

**Issue by fediskhakov** [QuantEcon/sphinxcontrib-jupyter#68]
Line 101 in  jupyter/builders/jupyter.py has "_static" hard coded in, should probably be jupyter_static_file_path insted
Moreover, it seems that the folder structure of the static file folders is not replicated in the compiled notebooks (instead, images are linked from the root directory where index resides).  Example: compile rst filed that are located in subfolders and have links to static files in those subfolders.

**Comment by mmcky** [comment]
PR #134 should resolve this issue
