### ISSUE TITLE
Allow definition for dependencies?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#7]
Should this extension provide a ``dependency`` directive which would allow users to supply a dependent file(s) for the notebook that is not shown in any notebook cells but is brought over to be included in the ``_static`` folder. 

This would be useful for support data files or python modules to import functions from

**Comment by jstac** [comment]
Sounds like a nice idea.

**Comment by mmcky** [comment]
dependency in `execution` has been implemented but not dependency on `_static` files. Given we have adopted a convention in QuantEcon to have fairly independent lectures -- this covers most bases as if a file is generated by a lecture needed by a future lecture (this can be accommodated for).

**Comment by mmcky** [comment]
this has been added with `jupyter_dependecy_lists`
