### ISSUE TITLE
Error rendering some LaTeX

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/sphinxcontrib-jupyter#74]
The QuantEcon [Kalman lecture](https://lectures.quantecon.org/jl/kalman.html) renders a bit of `LaTeX` incorrectly. In particular, see the line "[integral] indicates the probability that we attach to to the missile being..." For some reason, the integral is being moved to the end of line after I run Jupinx. 

cc: @nosferican, @mmcky. José, if you have time, maybe see if you could replicate the issue to confirm.

**Comment by mmcky** [comment]
thanks @arnavs I can replicate this on the comparison tool:

![image](https://user-images.githubusercontent.com/8263752/44696437-e193d100-aaba-11e8-988f-2b15bd1c5816.png)

**Comment by mmcky** [comment]
This has now been fixed as checked on the live site. Fixed by #114
