### ISSUE TITLE
FEAT: Include test option for compiling notebooks selective with and without code tests

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinxcontrib-jupyter#77]
Thanks @jlperla for the following:

@arnavs You can take a shot at this.  The basic idea is that we would introduce a `:class: test`  as a parallel to :class: solution`

The beautiful thing now is that we can almost use identical code wherever the word `solution` is used in the https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/72/files  

In partiular,
- in `sphinxcontrib/jupyter/__init__.py`
```
app.add_config_value("jupyter_drop_tests", False, "jupyter")
```
- in `sphinxcontrib/jupyter/writers/translate_code.py`  we need to parse the `test` class and add a flag in the visitor
```
self.test= _parse_class["test"]
```
Then in the visitor if we are in a test and the option is set to drop them, we just `pass` and don't output the code.  i.e.
```
 if self.solution and self.jupyter_drop_solutions:    
            pass
```
- In `tests/conf.py`  we set the option with `jupyter_drop_tests = True` or `jupyter_drop_solutions = False`
- Add tests, of course.

You can ask @mmcky  but I think a lot of the other stuff in the PR also does something with output blocks, which I believe is orthogonal?

**Comment by arnavs** [comment]
@mmcky I think we can close this now.

**Comment by mmcky** [comment]
thanks @arnavs
